tests: take advantage of new die function in common.sh.

diff --git a/tests/test-git b/tests/test-git
--- a/tests/test-git
+++ b/tests/test-git
@@ -16,10 +16,7 @@ check_git()
 find_gitrepo()
 {
     gitrepo="$testdir/git-repo.tar"
-    if [ ! -f $gitrepo ]; then
-        echo "$gitrepo not found" >&2
-        exit 1
-    fi
+    [ -f $gitrepo ] || die "$gitrepo not found"
 }
 
 pretest()
